import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";

import AuthProvider from "@/auth/auth-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { ToasterProvider } from "@/providers/toast-provider";
import { cn } from "@/lib/utils";


const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(`${poppins.variable}`,  "bg-white dark:bg-black flex flex-col")}>
        <ThemeProvider
              attribute="class"
              defaultTheme="white"
              enableSystem
              disableTransitionOnChange
        >
          <AuthProvider
            authType='cookie'
            authName='_auth'
          >
            {children}
          </AuthProvider>
        </ThemeProvider>
        <ToasterProvider />
      </body>
    </html>
  );
}
